### ISSUE TITLE
Question on vertexattribpointer "normalized" param

### ISSUE THREAD

**Issue by timknip** [cprogrammer1994/ModernGL#157]
Got vertexdata which needs vertexattribpointer's ```normalized``` param set to ```true```.

How would I go about that?

Thanks.

**Comment by cprogrammer1994** [comment]
Hi!

Currently the `normalized` parameter is set to `false`.

You can do 2 things:

1. Normalize the vectors with `numpy` then write the content directly to a `buffer`.
2. Normalize the vectors in the shader.

Solution 1. is good for static data (data calculated once rendered processed multiple times)
Solution 2. is a quick but it is not efficient.

**PS:** You can create a numpy array using `numpy.frombuffer`. Pass the buffer as the parameter. Set the numpy writeable flag to `True`. Reshape the numpy array. Normalize the numpy array in-place. Delete the numpy array (this step will ensure that the `glUnmapBuffer` is called).

The **PS** part could work, because the ModernGL Buffers implement the [Buffer Interface](https://docs.python.org/3/c-api/buffer.html)

**Comment by timknip** [comment]
Thanks!

Going for 1)
Complication: got interleaved buffer ;-)

```
vbo = ctx.buffer(vertices.astype('f4').tobytes())
ibo = ctx.buffer(indices.astype('i4').tobytes())

vao_content = [
    (vbo, '3f3f2f', ['in_vert', 'in_norm', 'in_text'])
]

vao = ctx.vertex_array(prog, vao_content, ibo)
```

But guess its possible with some numpy wizardry.

**Comment by cprogrammer1994** [comment]
I uploaded an example: [numpy_array_inplace_operations.py](https://github.com/cprogrammer1994/ModernGL/blob/master/examples/numpy_array_inplace_operations.py)

Correction:

ModernGL Buffers does not implement the buffer interface. **But** their internal object (`Buffer.mglo`) does.

**Comment by cprogrammer1994** [comment]
Hopefully this will be easier in the future once https://github.com/cprogrammer1994/ModernGL/issues/158 is done.

**Comment by cprogrammer1994** [comment]
VertexArrays can now bind individual vertex attributes setting the normalize parameter too (when applicable).

```py
VertexArray.bind(self, attribute, cls, buffer, fmt, *, offset=0, stride=0, divisor=0, normalize=False) -> None
```

I will add a couple of examples using this method.

---

The BufferFormat (the one that looks like this: `3f3f4f') will accept other then half floats and 1 byte floats too. so binding an attribute with the method above will be rare.

One can specify ie the color attribute (RGBA, 1 byte / color):

```py
ctx.vertex_array(prog, [
(vbo, '3f 3f 4f1', 'in_vert', 'in_norm', 'in_color'),
])

# in_vert `3f`
# in_norm `3f`
# in_color `4f1` ([4] [f]loats of [1] byte) 
```
