### ISSUE TITLE
Missing half-float as texture data type

### ISSUE THREAD

**Issue by pohlt** [cprogrammer1994/ModernGL#162]
Hi there,
Excellent OpenGL bindings! A breath of fresh air after pyopengl.

I couldn't find half-floats (16 bit floats) as a texture data type.
Did I miss something? Any plans to add this?

Cheers,
Tom

**Comment by cprogrammer1994** [comment]
Hi!

Currently you can have only `unsigned char` or `32bit float` as internal types.
Most of the framebuffer attachable objects have a parameter `floats=True or False` that specify the internal storage of the object.

I will replace the `floats` parameter with `dtype` (it will be similar to numpy's dtype)

This feature can only be part of ModernGL5 due to backward compatibility reasons.

**Comment by cprogrammer1994** [comment]
Half floats are supported in ModernGL5.
Tests were added [here](https://github.com/cprogrammer1994/ModernGL/commit/a57dfbb52b3fc25a33cdc531882fdff98ab1f592)

ModernGL5 will be released soon
