### ISSUE TITLE
should we add fake varying?

### ISSUE THREAD

**Issue by kunyao** [cprogrammer1994/ModernGL#170]
There is fake uniform now, but still, lack of strategy for fake varyings passing for the shaders as my comments in (https://github.com/cprogrammer1994/ModernGL/issues/154) which is not fully resolved I think.

**Comment by cprogrammer1994** [comment]
Changed `vertex_array` to support invalid attributes. (https://github.com/cprogrammer1994/ModernGL/commit/760c24599f192c8bcb0348648de38e7e07d1bf45)

Please test this feature. I will release it right after.

```
python -m pip install https://github.com/cprogrammer1994/ModernGL/archive/master.zip -U
```

Add an extra kwarg to your calls:

```
vertex_array(... skip_errors=True)
```

---

Unfortunately **invalid/non-existing** transform feedback **varyings** have no format or size. Not sure how to replace those with padding.

Consider the following example:

```py
ctx.program(
    vertex_shader='''
        #version 330

        uniform vec2 Acc;

        in vec2 in_pos;
        in vec2 in_prev;

        out vec2 out_pos;
        out vec2 out_prev;
        out vec2 out_something_else;

        void main() {
            out_pos = in_pos * 2.0 - in_prev + Acc;
            out_prev = in_pos;
        }
    ''',
    varyings=['out_pos', 'out_prev', 'out_something_else', 'out_something_else_x']
)
```

Both `out_something_else` and `out_something_else_x` are invalid. One could tell from the source code that the size of `out_something_else` is `2 floats`. This is not true for `out_something_else_x`.

Instead of parsing the source code, I think The following syntax would be a better solution:

**original**

```
varyings=['out_pos', 'out_prev', 'out_something_else', 'out_something_else_x']
```

**1st idea** (short)

```
varyings=['out_pos', 'out_prev', 'out_something_else/2f', 'out_something_else_x/4i']
varyings=['out_pos', 'out_prev', 'out_something_else|2f', 'out_something_else_x|4i']
varyings=['out_pos', 'out_prev', 'out_something_else|2', 'out_something_else_x|4']
```

Where `'foo|N'` means the following: use `gl_SkipComponentsN` when `foo` is not an active transform feedback varying.

**2nd idea**

```
varyings=['out_pos', 'out_prev', 'out_something_else | gl_SkipComponents2', 'out_something_else_x | gl_SkipComponents4']
```

Where `'foo|bar'` means the following: use `bar` when `foo` is not an active transform feedback varying.

---

What do you think?
