### ISSUE TITLE
TODO list?

### ISSUE THREAD

**Issue by einarf** [cprogrammer1994/ModernGL#197]
Do you have a todo list with tasks that needs to be done for this project you might want help with? It doesn't really matter what it is as long as it improves the project in any way.

**Comment by cprogrammer1994** [comment]
Hi!

I have started a [new branch](https://github.com/cprogrammer1994/ModernGL/tree/experimental) with some new features. Some of them were not easy to implement with 100% backward compatibility.

This branch does not have all the functionality implemented, most of the examples are working fine with a minimal touch.

Main reasons for the new development branch:

On the master:
The python layer is wrapping the c++ implementation. the c++ implementation has no information about the python layer.

On the experimental branch:
The python layer is wrapping the c++ implementation. the c++ implementation knows all the classes defined in the python layer and can access all their slots. the c++ implementation is capable of creating instances of classes defined in the python layer. (no ugly wrapping required). the c++ implementation can import numpy and Pillow but does not depend on them. dual build for debug version. (module is compiled twice (release + debug), create_context is allowed to choose between them. when debug is enabled checks can be performed, traces can be implemented without affecting the performance of applications using the release version of mgl.

New features:
- buffers can be immutable when supported
- textures can have immutable storage when supported
- buffers can be mapped (even as numpy arrays)
- buffers can be cleared
- textures can be cleared
- textures can be created directly passing a `PIL.Image`
- framebuffers support layered rendering
- framebuffers can be read as a numpy array / PIL.Image (not implemented yet)
- textures layers and mipmap levels are accessable (write, attach to fbo ...)

Non backward compatible changes:
- program uniforms should not be readable (it would be more convenient to have `program.__setitem__` as the value setter). On the master uniform getsetters have too much code regarding what they do. uniform buffers should be used over uniforms when possible.
- I think modenrgl.enable_only should become moderngl.enable (there will be no disable since enable_only provide a safer way to deal with those flags)
- buffer.orphan should be removed (to support immutable storage even better)
- texture3d and texture can be stored in the same class

Structural changes:
- the `src/` folder was moved to `moderngl/mgl/`
- mgl types are created dynamically

I have tried to collect all my thoughts on the experimental branch.

Are you interested in working on new features on this branch?

**Comment by einarf** [comment]
Looks very nice. Will definitely have a look. I might be tempted to start with something simpler like adding sampler support. Still very new to this project, but I'm hoping to contribute quite a bit.

Regarding uniforms: I hope it's still possible to ask a program about its uniforms possibly also knowing their types. That's an extremely useful feature for me at least making a framework over all this.

**Comment by cprogrammer1994** [comment]
I have added a branch with the minimum changes required to have a new type: https://github.com/cprogrammer1994/ModernGL/tree/sampler_sketch

This type has 1 method and 1 property with a getter and setter. If this feature requires any special interaction feel free to ask for help.

search for "TODO: impl sampler" to find files/lines where changes should be made.
I will have more time around the week end. I will be able to help more :)

PS: Will keep uniform value reading, the only difference will be that it will not be over optimized since ubos are better when it comes to optimization. Their type (the GLenum value) will also be accessible on the experimental branch.
