### ISSUE TITLE
Consider expanding the readme section on creating a window

### ISSUE THREAD

**Issue by NeilGirdhar** [cprogrammer1994/ModernGL#207]
I think it would be helpful to link to examples of how to create a window using the various libraries listed.  E.g., https://github.com/cprogrammer1994/ModernGL/blob/master/examples/qtmoderngl.py shows how to do it in PyQt.

Also, is there a reason that your easy-to-use https://github.com/cprogrammer1994/GLWindow is not listed?  It looks great.

**Comment by einarf** [comment]
I've created support for different window handlers, so I could look into adding some examples in this project: https://github.com/Contraz/demosys-py/tree/master/demosys/context

* The best choice so far has actually been PyQt5 because it works out of the box on all platforms.
* pyglfw if by far the easiest one to use, but requires the user to install glfw on the side. It's my personal #1 choice and works on all platforms.
* Pyglet doesn't work on OS X because it only support 2.1 forward compatible contexts and require some hacking to avoid fixed pipeline calls in the default window.

Looking into adding pygame as well (SDL2)

**Comment by einarf** [comment]
I would suggest only making examples for libraries supporting core contexts so users don't fall into the "my project doesn't work with driver X and platform Y"-trap. Right now pyglet is mentioned on README and could cause a lot of frustration for some users. Optionally include the example with a huge disclaimer.

I would suggest putting all the example windows in ``examples/windows`` and link that from the the root ``README.md``. We can keep adding a module there for each window type and make pretty ``README.md``.

**Comment by einarf** [comment]
#271 should be able to cover everything in this issue.

**Comment by einarf** [comment]
Should be closed unless you think there are more work remaining here.
