### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by cprogrammer1994** [cprogrammer1994/ModernGL#272]
Not sure if doable, but let's see.

- [x] The Android support can be tested with Pydroid3
- [x] the platform specific files are separated
- [x] moderngl installs on Pydroid3
- [ ] the platform specific methods are implemented (ex: loading OpenGL functions, creating a context)
- [ ] hello world from Pydroid3

**Comment by cprogrammer1994** [comment]
![moderngl-install-on-pydroid3](https://user-images.githubusercontent.com/11232402/51425638-8ee0c000-1be7-11e9-9863-128e0a25d250.jpg)

**Comment by cprogrammer1994** [comment]
The implementation can be tested with:

```py
import moderngl.experimental as mgl
ctx = mgl.create_context()
```

There is no implementation yet.

**Comment by cprogrammer1994** [comment]
Branch: https://github.com/cprogrammer1994/ModernGL/tree/android-support

Related source files:

https://github.com/cprogrammer1994/ModernGL/blob/9b85c698eb6b02cac0af2b3658c87c68d1ebfa4e/moderngl/experimental/mgl/internal/opengl/gl_context_android.cpp#L1-L25

https://github.com/cprogrammer1994/ModernGL/blob/9b85c698eb6b02cac0af2b3658c87c68d1ebfa4e/moderngl/experimental/mgl/internal/opengl/gl_methods.cpp#L49-L58

**Comment by cprogrammer1994** [comment]
Needs progress, will be reopen later

**Comment by jimy-byerley** [comment]
Hello 
Is there any news for an Android support ? I'm looking forward to use modernGL on a project running on a tablet. I'm considering running python directly on android, or in a chroot, or to install linux on the tablet. But the last two options seems tedious.

When I tried to `pip install moderngl` I got some error in the compilation of `glcontext` because the X11 headers are not found. 
But would it be difficult to add a support for Android ? Also do you think that's something I can eventually contribute to ?

**Comment by einarf** [comment]
You can definitely make a PR for the glcontext package. Make an android backend. glcontext has a very simple setup.
