### ISSUE TITLE
Support for linux

### ISSUE THREAD

**Issue by cprogrammer1994** [cprogrammer1994/ModernGL#4]

**Comment by cprogrammer1994** [comment]
glxinfo | grep OpenGL

**Comment by cprogrammer1994** [comment]
readelf -Ws /usr/lib/libGL.so.1

**Comment by cprogrammer1994** [comment]
testing on ubuntu:
linking fails (missing -lGL)
apt-get install libgl1-mesa-dev

**Comment by cprogrammer1994** [comment]
virtula machine has 1.2 GL support need to test on a real PC :smiley:

**Comment by cprogrammer1994** [comment]
fedora:
```
dnf install redhat-rpm-config
````

**Comment by stuaxo** [comment]
Are you on virtualbox or vmware?   They both vary in the their support of GL (and were both pretty incomplete last time I tried).

Not sure if installing the guest extensions in the vm would help, but worth a try.

Latest version of fedora *sounds* like it should be OK, though its only in the last year or so that 3.x and 4.x has fully come online on mesa - see  https://mesamatrix.net/

You also could try setting the environment variable ```MESA_GL_VERSION_OVERRIDE``` to ```3.0``` - I doubt it would make things work, but they may fail later on.

**Comment by cprogrammer1994** [comment]
I have Fedora on my ext HDD
Ubuntu in VMware
Fedora can detect my GPU (glxinfo prints GL4.1 support, far better then the VM with GL 1.2)

my GPU actually supports 4.4
